#########################
# Project Configuration #
#########################

language: cpp

sudo: true
dist: trusty

services:
  - docker

before_install:
  - docker pull registry.cn-hangzhou.aliyuncs.com/leosocy/opencv:3.4.1

jobs:
  include:
    - stage: tests
      script: echo $TRAVIS_BUILD_DIR
      script:
        - docker run --rm -v $TRAVIS_BUILD_DIR/$REPOSITORY:$TRAVIS_BUILD_DIR/$REPOSITORY
         -w $TRAVIS_BUILD_DIR/$REPOSITORY
         registry.cn-hangzhou.aliyuncs.com/leosocy/opencv:3.4.1
         sh -c 'mkdir build; cmake ../test; ./test_edcc'
    - stage: lint
      script:
        - echo "lint"